name: TheAPI
main: me.devtec.theapi.bukkit.BukkitLoader
version: 11.0
author: DevTec, StraikerinaCZ
website: https://www.spigotmc.org/resources/72679/
api-version: 1.13
softdepend: [Vault,PlaceholderAPI,HeadDatabase]
spigot-id: 72679